CREATE DATABASE TA14_Ejercicio_10;

USE TA14_Ejercicio_10;

CREATE TABLE PRODUCTOS (
codigo INT PRIMARY KEY,
nombre NVARCHAR(100),
precio INT
);

CREATE TABLE CAJEROS (
codigo INT PRIMARY KEY,
nom_apels NVARCHAR(255)
);

CREATE TABLE MAQUINAS_REGISTRADORAS (
codigo INT PRIMARY KEY,
piso INT
);

CREATE TABLE VENTAS (
codigo_productos INT NOT NULL,
codigo_cajeros INT NOT NULL,
codigo_maquinas INT NOT NULL,
KEY (codigo_productos),
FOREIGN KEY (codigo_productos) REFERENCES PRODUCTOS (codigo)
ON DELETE NO ACTION ON UPDATE CASCADE,
KEY (codigo_cajeros),
FOREIGN KEY (codigo_cajeros) REFERENCES CAJEROS (codigo)
ON DELETE NO ACTION ON UPDATE CASCADE,
KEY (codigo_maquinas),
FOREIGN KEY (codigo_maquinas) REFERENCES MAQUINAS_REGISTRADORAS (codigo)
ON DELETE NO ACTION ON UPDATE CASCADE,
PRIMARY KEY (codigo_productos, codigo_cajeros, codigo_maquinas)
);

SELECT * FROM PRODUCTOS;
SELECT * FROM CAJEROS;
SELECT * FROM MAQUINAS_REGISTRADORAS;
SELECT * FROM VENTAS;
