CREATE DATABASE TA14_Ejercicio_7;

USE TA14_Ejercicio_7;

CREATE TABLE DESPACHOS (
numero INT NOT NULL PRIMARY KEY,
capacidad INT NOT NULL
);

CREATE TABLE DIRECTORES (
dni VARCHAR(8) NOT NULL PRIMARY KEY,
nom_apels NVARCHAR(255),
dni_jefe VARCHAR(8) NOT NULL,
despacho INT NOT NULL,
KEY (dni_jefe),
FOREIGN KEY (dni_jefe) REFERENCES DIRECTORES (dni)
ON DELETE NO ACTION ON UPDATE CASCADE,
KEY (despacho),
FOREIGN KEY (despacho) REFERENCES DESPACHOS (numero)
ON DELETE NO ACTION ON UPDATE CASCADE
);

SELECT * FROM DESPACHOS;
SELECT * FROM DIRECTORES;
