CREATE DATABASE TA14_Ejercicio_8;

USE TA14_Ejercicio_8;

CREATE TABLE PIEZAS (
codigo INT PRIMARY KEY,
nombre NVARCHAR(100)
);

CREATE TABLE PROVEEDORES (
id CHAR(4) PRIMARY KEY,
nombre NVARCHAR(100)
);

CREATE TABLE SUMINISTRA (
codigo_pieza INT NOT NULL,
id_proveedores CHAR(4) NOT NULL,
precio INT,
KEY (codigo_pieza),
FOREIGN KEY (codigo_pieza) REFERENCES PIEZAS (codigo)
ON DELETE NO ACTION ON UPDATE CASCADE,
KEY (id_proveedores),
FOREIGN KEY (id_proveedores) REFERENCES PROVEEDORES (id)
ON DELETE NO ACTION ON UPDATE CASCADE,
PRIMARY KEY (codigo_pieza, id_proveedores)
);

SELECT * FROM PIEZAS;
SELECT * FROM PROVEEDORES;
SELECT * FROM SUMINISTRA;
